--1.
INSERT INTO TB_CLASS_TYPE VALUES ('01', '전공필수');
INSERT INTO TB_CLASS_TYPE VALUES ('02', '전공선택');
INSERT INTO TB_CLASS_TYPE VALUES ('03', '교양필수');
INSERT INTO TB_CLASS_TYPE VALUES ('04', '교양선택');
INSERT INTO TB_CLASS_TYPE VALUES ('05', '논문지도');
COMMIT;

--2.
CREATE TABLE TB_학생일반정보 AS
(SELECT STUDENT_NO, STUDENT_NAME, STUDENT_ADDRESS
 FROM TB_STUDENT);
 
 SELECT * FROM TB_학생일반정보;
 
 --3.
 CREATE TABLE TB_국어국문학과 AS
        (SELECT STUDENT_NO, STUDENT_NAME, (SUBSTR(STUDENT_SSN, 1, 2) + 1900) AS "출생년도", 
                PROFESSOR_NAME
         FROM TB_STUDENT
         JOIN TB_PROFESSOR ON(COACH_PROFESSOR_NO = PROFESSOR_NO)         
);
SELECT * FROM TB_국어국문학과;

--4.
UPDATE TB_DEPARTMENT
SET CAPACITY = ROUND(CAPACITY * 1.1);

--5.
UPDATE TB_STUDENT
SET STUDENT_ADDRESS = '서울시 종로구 숭인동 182-21'
WHERE STUDENT_NO = 'A413042';

SELECT STUDENT_ADDRESS FROM TB_STUDENT WHERE STUDENT_NO = 'A413042';

--6.
UPDATE TB_STUDENT t
SET t.STUDENT_SSN = (SELECT SUBSTR(s.STUDENT_SSN, 1, 6) 
                     FROM TB_STUDENT s 
                     WHERE s.STUDENT_NO = t.STUDENT_NO); ----???????
SELECT STUDENT_SSN FROM TB_STUDENT;

--7.
UPDATE TB_GRADE A 
SET POINT = 3.5
WHERE A.STUDENT_NO = (SELECT B.STUDENT_NO
                      FROM TB_STUDENT B
                      WHERE A.STUDENT_NO = B.STUDENT_NO
                      AND B.STUDENT_NAME = '김명훈')
AND TERM_NO = '200501'
AND A.CLASS_NO = (SELECT C.CLASS_NO
                  FROM TB_CLASS C
                  JOIN TB_DEPARTMENT USING(DEPARTMENT_NO)
                  WHERE )

SELECT STUDENT_NAME
FROM TB_STUDENT
WHERE STUDENT_NAME = '김명훈';

--8.
DELETE FROM TB_GRADE A
WHERE A.STUDENT_NO = (SELECT B.STUDENT_NO
                        FROM TB_STUDENT B WHERE B.STUDENT_NO = A.STUDENT_NO
                        AND ABSENCE_YN = 'Y');