--1.
SELECT STUDENT_NO, STUDENT_NAME, ENTRANCE_DATE
FROM TB_STUDENT 
WHERE DEPARTMENT_NO = '002'
ORDER BY DEPARTMENT_NO ASC;

--2.
SELECT PROFESSOR_NAME, PROFESSOR_SSN
FROM TB_PROFESSOR
WHERE PROFESSOR_NAME NOT LIKE '___';

--3.
SELECT PROFESSOR_NAME,
(EXTRACT(YEAR FROM SYSDATE) - (SUBSTR(PROFESSOR_SSN, 1, 2) + 1901)) AS "나이"
FROM TB_PROFESSOR
WHERE SUBSTR(PROFESSOR_SSN, 8, 1) IN ('1','3')
ORDER BY 나이;

--4.
SELECT SUBSTR(PROFESSOR_NAME, 2, 2) AS "이름"
FROM TB_PROFESSOR;

--5.
SELECT STUDENT_NO, STUDENT_NAME, 
(EXTRACT(YEAR FROM ENTRANCE_DATE) - (SUBSTR(STUDENT_SSN, 1, 2) + 1900)) AS "입학나이"
FROM TB_STUDENT
WHERE (EXTRACT(YEAR FROM ENTRANCE_DATE) - (SUBSTR(STUDENT_SSN, 1, 2) + 1900)) > 19;

--6.
SELECT TO_CHAR(TO_DATE(20201225), 'DAY') FROM DUAL;

--7.
SELECT TO_CHAR(TO_DATE('99/10/11'), 'YYYY"년" MM"월" DD"일"') FROM DUAL;
SELECT TO_CHAR(TO_DATE('49/10/11'), 'YYYY"년" MM"월" DD"일"') FROM DUAL;
SELECT TO_CHAR(TO_DATE('99/10/11'), 'RRRR"년" MM"월" DD"일"') FROM DUAL;
SELECT TO_CHAR(TO_DATE('49/10/11'), 'RRRR"년" MM"월" DD"일"') FROM DUAL;

--8.
SELECT STUDENT_NO, STUDENT_NAME
FROM TB_STUDENT
WHERE SUBSTR(STUDENT_NO, 1, 1) != 'A';

--9.
SELECT ROUND(AVG(POINT),1) AS "평점"
FROM TB_GRADE
WHERE STUDENT_NO = 'A517178';

--10.
SELECT DEPARTMENT_NO AS "학과번호", CAPACITY AS "학생 수(명)"
FROM TB_DEPARTMENT;

--11.
SELECT COUNT(*) 
FROM TB_STUDENT
WHERE COACH_PROFESSOR_NO IS NULL;

--12.
SELECT SUBSTR(TERM_NO, 1, 4) AS "년도", 
ROUND(AVG(POINT),1) AS "년도별 평점"
FROM TB_GRADE
WHERE STUDENT_NO = 'A112113'
GROUP BY SUBSTR(TERM_NO, 1, 4);


--13.
SELECT DEPARTMENT_NO, COUNT(*)
FROM TB_STUDENT
WHERE ABSENCE_YN = 'Y'
GROUP BY DEPARTMENT_NO;

--14.
SELECT STUDENT_NAME, COUNT(*)
FROM TB_STUDENT
GROUP BY STUDENT_NAME
HAVING COUNT(*) >= 2;

--15.
SELECT SUBSTR(TERM_NO, 1, 4) AS "년도", SUBSTR(TERM_NO, 5, 2) AS "학기",
POINT AS "평점"
FROM TB_GRADE
WHERE STUDENT_NO = 'A112113';