delete from MOVIE;
DROP TABLE MOVIE;
CREATE TABLE MOVIE(
   TITLE VARCHAR2(50 BYTE) NOT NULL ENABLE, 
    TYPE VARCHAR2(30 BYTE) NOT NULL ENABLE, 
    DIRECTOR VARCHAR2(30 BYTE) NOT NULL ENABLE, 
    RELYEAR VARCHAR2(30 BYTE), 
    AGELIMIT NUMBER
);

//DROP SEQUENCE SEQ_USERNO;
//CREATE SEQUENCE SEQ_USERNO
//NOCACHE;

SELECT * from MOVIE;
  